chore: Fix various spelling and typographical errors in source code comments and strings (Rules namespace).
microsoft/axe-windows pull request #739
Opened 2022-08-12 08:44 UTC by codeofdusk

#### Details
This PR fixes various spelling and typographical errors found in strings and comments in the `Rules` namespace.

##### Motivation
Motivated by errors discovered while working on microsoft/accessibility-insights-windows#1323.

##### Context
One of a series of PRs.

#### Pull request checklist

- [n/a] Addresses an existing issue: #0000

2022-08-12 16:58 UTC, DaveTryon commented on src/Rules/Resources/HowToFix.resx
> +    <value>The IsKeyboardFocusable property for a custom element should be true when the element supports actionable patterns.</value>
There should be a corresponding change in `HowToFix.Designer.cs`. These are automatically kept in sync if edited via the IDE, but require manual synchronization if the files are edited outside the IDE.

2022-08-12 16:58 UTC, DaveTryon commented on src/Rules/Resources/HowToFix.resx
>    </data>
There should be a corresponding changes in `HowToFix.Designer.cs`. These are automatically kept in sync if edited via the IDE, but require manual synchronization if the files are edited outside the IDE.

2022-08-12 16:59 UTC, DaveTryon commented on src/Rules/Resources/Descriptions.resx
> +    <value>The IsKeyboardFocusable property for a custom element should be true when the element supports actionable patterns.</value>
There should be a corresponding change in `Descriptions.Designer.cs`. These are automatically kept in sync if edited via the IDE, but require manual synchronization if the files are edited outside the IDE.

2022-08-12 16:59 UTC, DaveTryon commented on src/Rules/Resources/Descriptions.resx
> +    <value>An on-screen element must not have a null BoundingRectangle property.</value>
There should be a corresponding change in `Descriptions.Designer.cs`. These are automatically kept in sync if edited via the IDE, but require manual synchronization if the files are edited outside the IDE.

2022-08-12 17:00 UTC, DaveTryon requested changes
@codeofdusk, the changes all look good, but please add the corresponding changes in the `Designer.cs` files

2022-08-13 00:04 UTC, codeofdusk commented
@DaveTryon Those files were indeed modified on my system, but GitHub made it appear that those were auto-generated files and I wasn't sure whether to commit them. Updating.

2022-08-17 17:56 UTC, DaveTryon approved these changes
LGTM

2022-08-17 18:24 UTC, DaveTryon requested changes
@codeofdusk, we also need to update docs\RulesDescription.md, since some of the corrections are in the rule descriptions. To do this, just run RulesMD.exe that gets built by the RulesMD project and direct the output to overwrite the file:

`RulesMD -o ..\..\..\..\docs\RulesDescription.md`

Then add the file to your PR. Thanks @RobGallo for catching this :)

2022-08-17 18:39 UTC, DaveTryon approved these changes
LGTM! I'll merge this after the PR build succeeds

2022-08-17 19:22 UTC, merged